name: Libft macOS compile check CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stevejobs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make re
      run:  |
            make re
